CREATE TABLE IF NOT EXISTS PUBLIC.ewm
(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    APP CHARACTER VARYING(512) NOT NULL,
    URI CHARACTER VARYING(512) NOT NULL,
    IP CHARACTER VARYING(16) NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL
);


