CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING(64) NOT NULL,
    EMAIL CHARACTER VARYING(128) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    UNIQUE (EMAIL)
);






