version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - INIT_SCHEMA=classpath*:schema_postgres.sql
      - INIT_DATA=classpath*:data_postgres.sql
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQL10Dialect
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=evgeniy
      - SPRING_DATASOURCE_PASSWORD=evgeniy

  stats-db:
      image: postgres:14-alpine
      container_name: stats-db-container
      ports:
        - "6541:5432"
      environment:
        - POSTGRES_PASSWORD=evgeniy
        - POSTGRES_USER=evgeniy
        - POSTGRES_DB=stats
      volumes:
        - ./ewm-stats/service/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    #  - ewm-stats
    environment:
      - INIT_SCHEMA=classpath*:schema_postgres.sql
      - INIT_DATA=classpath*:data_postgres.sql
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQL10Dialect
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=evgeniy
      - SPRING_DATASOURCE_PASSWORD=evgeniy
  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=evgeniy
      - POSTGRES_USER=evgeniy
      - POSTGRES_DB=ewm
    volumes:
      - ./ewm-service/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
